{% set name = "rio-tiler" %}
{% set version = "3.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rio-tiler-{{ version }}.tar.gz
  sha256: e1da6185f697d0fa0e26d1775919adc92c6bd50f5ef3e4bfb7d5e71a2d1a4125

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - attrs
    - boto3
    - cachetools
    - httpx
    - morecantile >=3.0,<3.1
    - numexpr
    - numpy
    - pydantic
    - pystac >=0.5.4
    - python >=3.7
    - rasterio >=1.1.7
    - rio-color

test:
  imports:
    - rio_tiler
    - rio_tiler.cmap_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cogeotiff/rio-tiler
  summary: Rasterio plugin to read mercator tiles from Cloud Optimized GeoTIFF.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
    - nrweir
