{% set name = "rio-tiler" %}
{% set version = "2.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rio-tiler-{{ version }}.tar.gz
  sha256: 600655c19d5f441666cbd8ef99f0024ef83bd6d833a302ab0c92e30736b56171

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs
    - boto3
    - httpx
    - morecantile >=2.1,<2.2
    - numexpr
    - numpy
    - pydantic
    - pystac >=0.5.3
    - python >=3.6
    - rasterio >=1.1.7
    - requests
    - rio-color

test:
  imports:
    - rio_tiler
    - rio_tiler.cmap_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cogeotiff/rio-tiler
  summary: Rasterio plugin to read mercator tiles from Cloud Optimized GeoTIFF.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
    - nrweir
