{% set name = "rio-tiler" %}
{% set version = "3.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rio-tiler-{{ version }}.tar.gz
  sha256: 37a77239e05faa05ec9cf2f3012348c08b877d415e311823526ec357f9d64756

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.9
  run:
    - attrs
    - boto3
    - cachetools
    - httpx
    - morecantile >=3.1,<4.0
    - numexpr
    - numpy
    - pydantic
    - pystac >=0.5.4
    - python >=3.7,<3.9
    - rasterio >=1.1.7
    - rio-color

test:
  imports:
    - rio_tiler
    - rio_tiler.cmap_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cogeotiff/rio-tiler
  summary: User friendly Rasterio plugin to read raster datasets.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
    - nrweir
